version: '3'
services:
  app:
    image: auto_crawl
    container_name: auto_crawl
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app
    ports:
      - "3000:3000"
    command: ./start.sh
